<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/again_17_module_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [ ]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)
X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

/tmp/ipykernel_2243/2531464647.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
/tmp/ipykernel_2243/2531464647.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
/tmp/ipykernel_2243/2531464647.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
/tmp/ipykernel_2243/2531464647.py:8: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

In [ ]:
from torch.utils.data import Dataset,DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
   return self.features.shape[0]

  def __getitem__(self,index):
   return self.features[index],self.labels[index]

In [ ]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [ ]:
import torch.nn as nn

In [ ]:
class MySimpleNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
learning_rate = 0.001
epochs = 100

In [ ]:
loss_function = nn.BCELoss()

In [ ]:
model = MySimpleNN(X_train_tensor.shape[1])

In [ ]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate,momentum=0.9)

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.5192076563835144
 2 , Loss = 0.4088127315044403
 3 , Loss = 0.3605370819568634
 4 , Loss = 0.22458691895008087
 5 , Loss = 0.30742987990379333
 6 , Loss = 0.21422283351421356
 7 , Loss = 0.1466151922941208
 8 , Loss = 0.1541053056716919
 9 , Loss = 0.1430487334728241
 10 , Loss = 0.3648454546928406
 11 , Loss = 0.11054954677820206
 12 , Loss = 0.15021558105945587
 13 , Loss = 0.16570530831813812
 14 , Loss = 0.2592319846153259
 15 , Loss = 0.14328868687152863
 16 , Loss = 0.07722458988428116
 17 , Loss = 0.21483871340751648
 18 , Loss = 0.09690786153078079
 19 , Loss = 0.2169075310230255
 20 , Loss = 0.19297687709331512
 21 , Loss = 0.20026682317256927
 22 , Loss = 0.14369477331638336
 23 , Loss = 0.10964661091566086
 24 , Loss = 0.16138562560081482
 25 , Loss = 0.18113885819911957
 26 , Loss = 0.10801059752702713
 27 , Loss = 0.17149387300014496
 28 , Loss = 0.17832709848880768
 29 , Loss = 0.1394258290529251
 30 , Loss = 0.09443795680999756
 31 , Loss = 0.04749429598450661
 32 , Loss = 0.17171569168567657
 33 , Loss = 0.05303608626127243
 34 , Loss = 0.09716224670410156
 35 , Loss = 0.23436419665813446
 36 , Loss = 0.0353495292365551
 37 , Loss = 0.1858978122472763
 38 , Loss = 0.04271847382187843
 39 , Loss = 0.11914603412151337
 40 , Loss = 0.0838814303278923
 41 , Loss = 0.11366366595029831
 42 , Loss = 0.03195890039205551
 43 , Loss = 0.317295104265213
 44 , Loss = 0.0482453890144825
 45 , Loss = 0.059038665145635605
 46 , Loss = 0.2497703582048416
 47 , Loss = 0.06869479268789291
 48 , Loss = 0.06294874101877213
 49 , Loss = 0.1415737122297287
 50 , Loss = 0.15742667019367218
 51 , Loss = 0.12926742434501648
 52 , Loss = 0.19766247272491455
 53 , Loss = 0.31620246171951294
 54 , Loss = 0.10094184428453445
 55 , Loss = 0.3195452094078064
 56 , Loss = 0.07874540239572525
 57 , Loss = 0.11030956357717514
 58 , Loss = 0.10430958122015
 59 , Loss = 0.029770627617836
 60 , Loss = 0.28862980008125305
 61 , Loss = 0.1070273369550705
 62 , Loss = 0.12475169450044632
 63 , Loss = 0.15628862380981445
 64 , Loss = 0.12998521327972412
 65 , Loss = 0.16191431879997253
 66 , Loss = 0.03837832435965538
 67 , Loss = 0.19964906573295593
 68 , Loss = 0.0768641009926796
 69 , Loss = 0.04067681357264519
 70 , Loss = 0.0558120496571064
 71 , Loss = 0.15953464806079865
 72 , Loss = 0.12396416813135147
 73 , Loss = 0.14951825141906738
 74 , Loss = 0.017633484676480293
 75 , Loss = 0.1392490267753601
 76 , Loss = 0.1328737586736679
 77 , Loss = 0.05977094545960426
 78 , Loss = 0.03359168767929077
 79 , Loss = 0.03881293535232544
 80 , Loss = 0.015233037061989307
 81 , Loss = 0.03602925315499306
 82 , Loss = 0.11851076036691666
 83 , Loss = 0.38771381974220276
 84 , Loss = 0.087828628718853
 85 , Loss = 0.09601704776287079
 86 , Loss = 0.10111873596906662
 87 , Loss = 0.2469933032989502
 88 , Loss = 0.42833560705184937
 89 , Loss = 0.04861227050423622
 90 , Loss = 0.029959363862872124
 91 , Loss = 0.3327313959598541
 92 , Loss = 0.025468911975622177
 93 , Loss = 0.016263926401734352
 94 , Loss = 0.025245917961001396
 95 , Loss = 0.10337106883525848
 96 , Loss = 0.03018363192677498
 97 , Loss = 0.10422667115926743
 98 , Loss = 0.08779134601354599
 99 , Loss = 0.013995736837387085
 100 , Loss = 0.08841656148433685

In [ ]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.549861490726471

In [ ]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate,momentum=0.9 )

#define loop
batch_size = 32
epoch = 100
n_sample = len(X_train_tensor)

for epoch in range(epochs):

  for start_indx in range(0,n_sample,batch_size):
    end_indx = start_indx + batch_size

    print(f" Start index {start_indx}, end indx {end_indx}\n")

    X_batch = X_train_tensor[start_indx:end_indx]
    y_batch = y_train_tensor[start_indx:end_indx]

    #forward pass
    y_pred = model(X_batch)
    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #upate step

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



  #print loss in each epoch

  # print(f" {epoch+1} , Loss = {loss.item()} ")

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160

 Start index 160, end indx 192

 Start index 192, end indx 224

 Start index 224, end indx 256

 Start index 256, end indx 288

 Start index 288, end indx 320

 Start index 320, end indx 352

 Start index 352, end indx 384

 Start index 384, end indx 416

 Start index 416, end indx 448

 Start index 448, end indx 480

 Start index 0, end indx 32

 Start index 32, end indx 64

 Start index 64, end indx 96

 Start index 96, end indx 128

 Start index 128, end indx 160


In [ ]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.984375