<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/Diabetes_Risk_Prediction_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/content/diabetes_risk_dataset.csv")
df.head()

,Patient_ID,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,1,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,2,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,3,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,4,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,5,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  6000 non-null   int64
 1   age                         6000 non-null   int64
 2   gender                      6000 non-null   object
 3   bmi                         6000 non-null   float64
 4   blood_pressure              6000 non-null   int64
 5   fasting_glucose_level       6000 non-null   int64
 6   insulin_level               6000 non-null   float64
 7   HbA1c_level                 6000 non-null   float64
 8   cholesterol_level           6000 non-null   int64
 9   triglycerides_level         6000 non-null   int64
 10  physical_activity_level     6000 non-null   object
 11  daily_calorie_intake        6000 non-null   int64
 12  sugar_intake_grams_per_day  6000 non-null   float64
 13  sleep_hours                 6000 non-null   float64
 14  stress_level                6000 non-null   int64
 15  family_history_diabetes     6000 non-null   object
 16  waist_circumference_cm      6000 non-null   float64
 17  diabetes_risk_score         6000 non-null   float64
 18  diabetes_risk_category      6000 non-null   object
dtypes: float64(7), int64(8), object(4)
memory usage: 890.8+ KB

In [7]:
df.columns

Index(['Patient_ID', 'age', 'gender', 'bmi', 'blood_pressure',
       'fasting_glucose_level', 'insulin_level', 'HbA1c_level',
       'cholesterol_level', 'triglycerides_level', 'physical_activity_level',
       'daily_calorie_intake', 'sugar_intake_grams_per_day', 'sleep_hours',
       'stress_level', 'family_history_diabetes', 'waist_circumference_cm',
       'diabetes_risk_score', 'diabetes_risk_category'],
      dtype='object')

In [8]:
df.drop(columns=['Patient_ID'], inplace=True)

In [9]:
df.head()

,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [10]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,6000.0,52.230667,18.757508,20.0,36.0,53.00,68.00,84.0
bmi,6000.0,32.939667,7.510155,16.0,26.9,32.75,38.50,50.0
blood_pressure,6000.0,144.482500,17.867248,91.0,132.0,144.00,157.00,200.0
fasting_glucose_level,6000.0,106.105500,31.213994,60.0,87.0,96.00,114.00,281.0
insulin_level,6000.0,15.080333,9.245581,2.0,7.1,13.80,21.00,55.9
HbA1c_level,6000.0,5.784583,0.956614,4.1,5.2,5.50,6.10,11.0
cholesterol_level,6000.0,217.490667,24.888595,139.0,200.0,217.00,234.00,309.0
triglycerides_level,6000.0,177.351500,51.897606,50.0,137.0,173.00,213.00,383.0
daily_calorie_intake,6000.0,2479.547000,548.410642,1200.0,2055.0,2385.00,2848.25,5249.0
sugar_intake_grams_per_day,6000.0,66.555733,39.576891,0.0,35.1,58.30,89.30,255.0
sleep_hours,6000.0,6.998700,1.331378,4.0,6.1,7.10,8.00,10.0
stress_level,6000.0,5.086500,2.342989,1.0,3.0,5.00,7.00,10.0
waist_circumference_cm,6000.0,105.049600,25.079335,60.0,84.7,104.60,124.20,150.0
diabetes_risk_score,6000.0,48.691417,37.242034,0.0,12.9,43.90,88.80,100.0

In [11]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
blood_pressure                0
fasting_glucose_level         0
insulin_level                 0
HbA1c_level                   0
cholesterol_level             0
triglycerides_level           0
physical_activity_level       0
daily_calorie_intake          0
sugar_intake_grams_per_day    0
sleep_hours                   0
stress_level                  0
family_history_diabetes       0
waist_circumference_cm        0
diabetes_risk_score           0
diabetes_risk_category        0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df['diabetes_risk_category'].unique()

array(['Prediabetes', 'Low Risk', 'High Risk'], dtype=object)

In [14]:
df.head()

,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [15]:
df['age_bin'] = pd.cut(df['age'],bins=[0,30,50,70,100],labels=['young','middle_aged','old','very_old'])

In [16]:
df.drop(columns=['age'], inplace=True)

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['diabetes_risk_category'] = le.fit_transform(df['diabetes_risk_category'])

In [18]:
df.head()

,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category,age_bin
0,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,2,very_old
1,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,1,old
2,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,0,young
3,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,0,young
4,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,2,old

In [19]:
df['age'] = le.fit_transform(df['age_bin'])

In [20]:
df.drop(columns=['age_bin'], inplace=True)

In [21]:
df.head()

,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category,age
0,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,2,2
1,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,1,1
2,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,0,3
3,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,0,3
4,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,2,1

In [22]:
X = df.drop('diabetes_risk_category',axis=1)
y = df['diabetes_risk_category']

In [23]:
numeric_features = X.select_dtypes(include = ['int64','float64']).columns
categorical_features = X.select_dtypes(include = ['object']).columns

In [24]:
numeric_features

Index(['bmi', 'blood_pressure', 'fasting_glucose_level', 'insulin_level',
       'HbA1c_level', 'cholesterol_level', 'triglycerides_level',
       'daily_calorie_intake', 'sugar_intake_grams_per_day', 'sleep_hours',
       'stress_level', 'waist_circumference_cm', 'diabetes_risk_score', 'age'],
      dtype='object')

In [25]:
categorical_features

Index(['gender', 'physical_activity_level', 'family_history_diabetes'], dtype='object')

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [27]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

class IQRHandler(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        self.Q1 = np.percentile(X, 25, axis=0)
        self.Q3 = np.percentile(X, 75, axis=0)
        self.IQR = self.Q3 - self.Q1
        return self

    def transform(self, X):
        lower = self.Q1 - 1.5 * self.IQR
        upper = self.Q3 + 1.5 * self.IQR
        return np.clip(X, lower, upper)

In [28]:
numerical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('outlier', IQRHandler()),
    ('scaler', StandardScaler())
])

In [29]:
categorical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore')),
])

In [30]:
combine_pipe = ColumnTransformer(transformers=[
    ('num', numerical_pipe, numeric_features),
    ('cat', categorical_pipe, categorical_features)
]
)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [33]:
X_train_transformed = combine_pipe.fit_transform(X_train)

In [34]:
X_test_transformed = combine_pipe.transform(X_test)

In [35]:
X_train_transformed

array([[-0.14489431,  0.48772886, -0.66291544, ...,  1.        ,
         1.        ,  0.        ],
       [-0.48022879,  0.76807935, -0.44046059, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.03548309,  1.32878032,  1.25019622, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.65990846,  0.48772886,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       [-0.96311045, -1.19437407, -1.19680706, ...,  0.        ,
         1.        ,  0.        ],
       [-1.37892522, -1.64293485, -0.84087931, ...,  0.        ,
         1.        ,  0.        ]])

In [36]:
X_test_transformed

array([[ 1.54519151,  1.66520091,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.43188101,  1.16057003, -0.48495156, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.06230985,  2.56232247,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.28503156, -0.577603  , -0.84087931, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.15020004,  0.71200925,  1.25019622, ...,  0.        ,
         0.        ,  1.        ],
       [-1.04359073, -1.30651426, -0.97435222, ...,  0.        ,
         1.        ,  0.        ]])

In [37]:
import torch
X_train_tensor = torch.from_numpy(X_train_transformed)
X_test_tensor = torch.from_numpy(X_test_transformed)

In [38]:
type(X_train_tensor)

torch.Tensor

In [39]:
type(X_test_tensor)

torch.Tensor

In [40]:
X_test_tensor.shape[1]

21

In [41]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    #clamp
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    # Calculate individual losses and then take the mean to get a scalar loss
    loss = -y*torch.log(y_pred)-(1-y)*torch.log(1-y_pred)
    return loss.mean()

In [42]:
model = MySimpleNN(X_test_tensor)

In [43]:
model.weights

tensor([[-1.2976],
        [-1.7124],
        [-1.0547],
        [-0.2171],
        [ 1.7541],
        [-0.4174],
        [ 0.3873],
        [-2.3161],
        [-1.2720],
        [ 0.9419],
        [ 0.2420],
        [ 0.0275],
        [-0.3995],
        [-0.4139],
        [-0.6587],
        [-0.2797],
        [ 0.3045],
        [ 1.2775],
        [-1.4652],
        [-0.0203],
        [-0.6591]], dtype=torch.float64, requires_grad=True)

In [44]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [45]:
learning_rate = 0.1
epochs = 25

In [46]:
model = MySimpleNN(X_train_tensor)

#define loop
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  #loss calcultor
  # Convert y_train to a tensor and pass it as the target variable
  y_train_tensor = torch.tensor(y_train.values, dtype=torch.float64).reshape(-1, 1)
  loss = model.loss_function(y_pred, y_train_tensor)

  #backward
  loss.backward()

  #update
  with torch.no_grad(): # Perform updates without tracking gradients
    model.weights.data -= learning_rate * model.weights.grad
    model.bias.data -= learning_rate * model.bias.grad

  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"{epoch+1}, loss ={loss.item()}")

1, loss =2.559757695704525
2, loss =2.2565067316974585
3, loss =1.9939345322446336
4, loss =1.7694065226697369
5, loss =1.578846027973965
6, loss =1.4175087260186885
7, loss =1.280631131115923
8, loss =1.1638618392467888
9, loss =1.0634690341775799
10, loss =0.9763806904450917
11, loss =0.9001282141362617
12, loss =0.8327510766673173
13, loss =0.7726972870468358
14, loss =0.7187355478386128
15, loss =0.6698837268097466
16, loss =0.6253530137788372
17, loss =0.5845051937922572
18, loss =0.5468201395954408
19, loss =0.5118709875951082
20, loss =0.47930502663071467
21, loss =0.44882885716401144
22, loss =0.42019678414785777
23, loss =0.39320169028310265
24, loss =0.36766782933400133
25, loss =0.3434451135433653

In [47]:
#y_pred = model.forward(X_test_tensor)

In [48]:
#y_pred = (y_pred>0.9).float()

In [49]:
#y_pred

In [50]:
#accuracy = (y_pred == y_test.values).float().mean()

In [51]:
#accuracy

In [52]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float() # threshold 0.5
  y_test_tensor = torch.tensor(y_test.values).float().view(-1,1)
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.6666666865348816

In [55]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test_tensor, y_pred))
print(classification_report(y_test_tensor, y_pred))

[[407 173   0]
 [ 52 593   0]
 [103 172   0]]
              precision    recall  f1-score   support

         0.0       0.72      0.70      0.71       580
         1.0       0.63      0.92      0.75       645
         2.0       0.00      0.00      0.00       275

    accuracy                           0.67      1500
   macro avg       0.45      0.54      0.49      1500
weighted avg       0.55      0.67      0.60      1500

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

# Version1

In [56]:
import torch
import torch.nn as nn

In [58]:
class Model(nn.Module):
  def __init__(self,num_features):
    super(Model,self).__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [59]:
features = torch.rand(10,5)

In [60]:
features

tensor([[0.5103, 0.5141, 0.8252, 0.5697, 0.5610],
        [0.5397, 0.6993, 0.4317, 0.6956, 0.8067],
        [0.0706, 0.9599, 0.5132, 0.9888, 0.2957],
        [0.6347, 0.4875, 0.8770, 0.4656, 0.5567],
        [0.8488, 0.0704, 0.1878, 0.6197, 0.7510],
        [0.1362, 0.1896, 0.7376, 0.4045, 0.3646],
        [0.1515, 0.9868, 0.7044, 0.4262, 0.3444],
        [0.9253, 0.7996, 0.5647, 0.9204, 0.2647],
        [0.4223, 0.5739, 0.8118, 0.9686, 0.4469],
        [0.9050, 0.7103, 0.1632, 0.6946, 0.4536]])

In [62]:
features.shape[1]

5

In [63]:
model = Model(features.shape[1])

In [66]:
#calling model for forwar pass
#model.forward(features)

model(features)

tensor([[0.4447],
        [0.3972],
        [0.4125],
        [0.4409],
        [0.4265],
        [0.4816],
        [0.3934],
        [0.3923],
        [0.4619],
        [0.3592]], grad_fn=<SigmoidBackward0>)

In [67]:
#show weights
model.linear.weight

Parameter containing:
tensor([[-0.1848, -0.4393,  0.3390,  0.2089, -0.0047]], requires_grad=True)