<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/DPM13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [73]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [74]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [75]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [76]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [77]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [78]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [79]:
len(df.columns)

31

In [80]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [81]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [82]:
X_train

array([[-0.11050074,  0.68708063, -0.06506209, ...,  0.7833575 ,
         0.26426214,  0.52249851],
       [-0.59143074, -1.36340661, -0.5886731 , ..., -0.6154943 ,
        -0.20093128, -0.17215479],
       [-0.87715973, -1.04135268, -0.89629458, ..., -0.89071018,
        -0.49809497,  0.42760052],
       ...,
       [-1.10347973, -1.64607264, -1.082831  , ..., -0.71991753,
         0.04177833, -0.35110529],
       [-0.51504774,  0.67086208, -0.50604074, ..., -0.49548998,
        -0.9990725 ,  0.38638768],
       [ 0.52885326, -0.88380112,  0.55549878, ...,  1.24479731,
         0.16935646,  0.40916319]])

In [83]:
y_train

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1])

# convert to tensor

In [84]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

#change dtype

X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)

y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

/tmp/ipython-input-699/1555669276.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
/tmp/ipython-input-699/1555669276.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
/tmp/ipython-input-699/1555669276.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
/tmp/ipython-input-699/1555669276.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

In [85]:
type(X_train_tensor)

torch.Tensor

In [86]:
class MySimpleNN():
  def __init__(self,X):
    self.weights= torch.rand(X.shape[1],1,dtype=torch.float32,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float32,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred


  def loss_function(self,y_pred,y):
      epsilon = 1e-7
      y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

      loss = -(y_train_tensor*torch.log(y_pred)+(1-y_train_tensor)*torch.log(1-y_pred)).mean()

      return loss

In [87]:
torch.rand(30,1)

tensor([[0.4042],
        [0.5769],
        [0.9115],
        [0.4273],
        [0.7996],
        [0.6682],
        [0.3148],
        [0.2028],
        [0.1171],
        [0.4124],
        [0.0987],
        [0.7089],
        [0.3585],
        [0.7404],
        [0.2517],
        [0.7850],
        [0.0582],
        [0.1451],
        [0.2251],
        [0.7589],
        [0.1973],
        [0.2310],
        [0.9503],
        [0.3438],
        [0.2298],
        [0.1944],
        [0.5621],
        [0.4424],
        [0.5123],
        [0.6781]])

In [88]:
model = MySimpleNN(X_train_tensor)

In [89]:
model.weights

tensor([[0.2432],
        [0.0512],
        [0.7856],
        [0.7335],
        [0.3788],
        [0.4198],
        [0.9526],
        [0.2467],
        [0.8852],
        [0.9643],
        [0.0225],
        [0.7644],
        [0.8112],
        [0.1611],
        [0.3208],
        [0.9438],
        [0.1160],
        [0.7634],
        [0.7666],
        [0.7468],
        [0.2812],
        [0.6234],
        [0.4614],
        [0.6863],
        [0.8515],
        [0.6193],
        [0.6884],
        [0.8143],
        [0.0704],
        [0.9329]], requires_grad=True)

In [90]:
lr = 0.1
epochs = 25

In [91]:
#Pipeline

model = MySimpleNN(X_train_tensor)

for epoch in range(epochs):

  #forward pass
  y_pred = model.forward(X_train_tensor)


  #loss
  loss = model.loss_function(y_pred,y_train_tensor)
  #backward
  loss.backward()

  #parameters
  with torch.no_grad():
    model.weights -= lr*model.weights.grad
    model.bias -= lr*model.bias.grad


  #zero gradient

  model.weights.grad.zero_()
  model.bias.grad.zero_()



  print(f"{epoch+1}, Loss = {loss.item()}")

1, Loss = 4.18323278427124
2, Loss = 4.078640460968018
3, Loss = 3.9716382026672363
4, Loss = 3.8592474460601807
5, Loss = 3.737574577331543
6, Loss = 3.6073946952819824
7, Loss = 3.474003553390503
8, Loss = 3.338369369506836
9, Loss = 3.1976394653320312
10, Loss = 3.048938035964966
11, Loss = 2.891545057296753
12, Loss = 2.7338948249816895
13, Loss = 2.5664920806884766
14, Loss = 2.394745349884033
15, Loss = 2.2170732021331787
16, Loss = 2.0396382808685303
17, Loss = 1.86324942111969
18, Loss = 1.686440348625183
19, Loss = 1.5151982307434082
20, Loss = 1.3571453094482422
21, Loss = 1.2148561477661133
22, Loss = 1.0911728143692017
23, Loss = 0.9881769418716431
24, Loss = 0.906791090965271
25, Loss = 0.8462627530097961

## Model Evalution

In [92]:
y_pred = model.forward(X_train_tensor)
y_pred = (y_pred>0.9).float()

accuracy = (y_pred==y_train_tensor).float().mean()
print(f"Accuracy = {accuracy}")

Accuracy = 0.6118971109390259

In [93]:
X_train_tensor.shape[1]

30