<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/DPM14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [341]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [342]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [343]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [344]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [345]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [346]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [347]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [348]:
len(df.columns)

31

In [349]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [350]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [351]:
X_train

array([[-0.87209828, -0.47105926, -0.80763259, ...,  0.65003095,
        -0.57652682,  0.62195685],
       [-0.49804031,  2.49969917, -0.57046084, ..., -1.73303886,
        -0.79224079, -0.91453424],
       [-1.30514231,  0.41528292, -1.29197982, ..., -0.73429507,
        -0.01995187,  0.44511438],
       ...,
       [-0.36855871, -1.26667349, -0.38872642, ..., -0.76096093,
        -0.85810764, -0.81592115],
       [-1.10516516,  0.08494017, -1.09940803, ..., -1.39098023,
        -1.03430149, -0.91508515],
       [-0.3973324 ,  1.10388472, -0.40664977, ...,  0.07533566,
        -0.10557878,  0.65115514]])

In [352]:
y_train

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

# convert to tensor

In [353]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

#change dtype

X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)

y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

/tmp/ipython-input-587/1555669276.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

In [354]:
type(X_train_tensor)

torch.Tensor

In [355]:
X_train.shape[1]

30

In [356]:
import torch.nn as nn

In [357]:
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
      super().__init__()

      self.linear = nn.Linear(num_features,1)
      self.sigmoid = nn.Sigmoid()


    def forward(self,features):
      out = self.linear(features)
      out = self.sigmoid(out)


      return out

In [358]:
torch.rand(30,1)

tensor([[0.9736],
        [0.5689],
        [0.2284],
        [0.5880],
        [0.3247],
        [0.2380],
        [0.6238],
        [0.6623],
        [0.2408],
        [0.3468],
        [0.9261],
        [0.9046],
        [0.9881],
        [0.8636],
        [0.7247],
        [0.6072],
        [0.0765],
        [0.1233],
        [0.3585],
        [0.4477],
        [0.2887],
        [0.8462],
        [0.6915],
        [0.6402],
        [0.6888],
        [0.2413],
        [0.0746],
        [0.6397],
        [0.0578],
        [0.4735]])

In [359]:
X_train_tensor.shape[1]

30

In [360]:
learning_rate = 0.1
epochs=50

In [361]:
loss_function = nn.BCELoss()

In [362]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [363]:
model = MySimpleNN(X_train_tensor.shape[1])

In [364]:
model.parameters()

In [365]:
X_test_tensor.dtype

torch.float32

In [366]:
model.linear.weight.dtype

torch.float32

In [367]:
y_train_tensor.dtype

torch.float32

In [368]:
model.parameters()

In [369]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

   #zero gradient
  optimizer.zero_grad()


  #backward pass
  loss.backward()


  #parameter update
  optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.6669823527336121
 2 , Loss = 0.5280845165252686
 3 , Loss = 0.45119917392730713
 4 , Loss = 0.4010954797267914
 5 , Loss = 0.3651624023914337
 6 , Loss = 0.3377794921398163
 7 , Loss = 0.3160172402858734
 8 , Loss = 0.2981816232204437
 9 , Loss = 0.2832169830799103
 10 , Loss = 0.27042701840400696
 11 , Loss = 0.2593316435813904
 12 , Loss = 0.249587744474411
 13 , Loss = 0.24094240367412567
 14 , Loss = 0.23320487141609192
 15 , Loss = 0.22622790932655334
 16 , Loss = 0.2198958396911621
 17 , Loss = 0.21411633491516113
 18 , Loss = 0.20881474018096924
 19 , Loss = 0.20392978191375732
 20 , Loss = 0.19941069185733795
 21 , Loss = 0.19521507620811462
 22 , Loss = 0.19130705296993256
 23 , Loss = 0.18765614926815033
 24 , Loss = 0.18423619866371155
 25 , Loss = 0.1810246706008911
 26 , Loss = 0.17800192534923553
 27 , Loss = 0.17515085637569427
 28 , Loss = 0.17245645821094513
 29 , Loss = 0.16990549862384796
 30 , Loss = 0.16748620569705963
 31 , Loss = 0.16518814861774445
 32 , Loss = 0.16300199925899506
 33 , Loss = 0.1609193980693817
 34 , Loss = 0.15893277525901794
 35 , Loss = 0.1570354402065277
 36 , Loss = 0.1552211493253708
 37 , Loss = 0.15348440408706665
 38 , Loss = 0.15182004868984222
 39 , Loss = 0.1502235233783722
 40 , Loss = 0.14869055151939392
 41 , Loss = 0.1472172737121582
 42 , Loss = 0.14580011367797852
 43 , Loss = 0.14443577826023102
 44 , Loss = 0.14312124252319336
 45 , Loss = 0.14185373485088348
 46 , Loss = 0.14063066244125366
 47 , Loss = 0.1394496113061905
 48 , Loss = 0.13830839097499847
 49 , Loss = 0.13720490038394928
 50 , Loss = 0.1361372172832489

In [370]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.5304709076881409

In [371]:
X_train_tensor.shape

torch.Size([455, 30])

In [372]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [373]:
from torchinfo import summary
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================

# Version1

In [374]:
import torch
import torch.nn as nn

In [375]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

# Version2

In [376]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()

    self.linear1 = nn.Linear(num_features,3) # Changed output features to 3
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()


  def forward(self,features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

# Version3

In [377]:
class Model(nn.Module):
  def __init__(self,num_features):
    super().__init__()


    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out = self.network(features)

    return out

In [378]:
#created dataset

features = torch.rand(10,5)

In [379]:
features

tensor([[0.5324, 0.8696, 0.6481, 0.9635, 0.2289],
        [0.1488, 0.0882, 0.7168, 0.7317, 0.3763],
        [0.7262, 0.5786, 0.7349, 0.1595, 0.2460],
        [0.4771, 0.1902, 0.2669, 0.6163, 0.9538],
        [0.3155, 0.0197, 0.7703, 0.3432, 0.9592],
        [0.7925, 0.7833, 0.9947, 0.0235, 0.1923],
        [0.7678, 0.6133, 0.5595, 0.9131, 0.2015],
        [0.0538, 0.8821, 0.1704, 0.6720, 0.2911],
        [0.1585, 0.6614, 0.2596, 0.9482, 0.4427],
        [0.5234, 0.3086, 0.2505, 0.2215, 0.5896]])

In [380]:
features.shape[1]

5

In [381]:
model = Model(features.shape[1])

In [382]:
#calling model for forward
model(features)

tensor([[0.4374],
        [0.4732],
        [0.4354],
        [0.4829],
        [0.4638],
        [0.4095],
        [0.4519],
        [0.4637],
        [0.4712],
        [0.4759]], grad_fn=<SigmoidBackward0>)

In [383]:
model.network[0].weight

Parameter containing:
tensor([[ 0.1279,  0.2651,  0.3693, -0.0987,  0.1283],
        [-0.1370,  0.4217,  0.1805,  0.0129, -0.2677],
        [-0.0608,  0.2201, -0.3381,  0.3469, -0.0236]], requires_grad=True)

In [384]:
model.network[2].weight

Parameter containing:
tensor([[-0.5120, -0.1563, -0.0090]], requires_grad=True)

In [385]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [386]:
from torchinfo import summary

summary(model, input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

# Training Pipeline