<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/DPM13%2614.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [68]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [69]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [70]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [71]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [72]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [73]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [74]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [75]:
len(df.columns)

31

In [76]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [77]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [78]:
X_train

array([[-0.53423041, -0.65556378, -0.54449854, ..., -0.44200965,
        -0.45043852, -0.45930421],
       [ 1.48914889,  1.32609374,  1.41302864, ...,  0.4576136 ,
        -0.9811378 , -1.29137461],
       [ 0.17728759,  0.20673766,  0.13867885, ..., -0.21560446,
        -0.85703582, -1.01292154],
       ...,
       [-0.1284428 ,  0.6928046 , -0.08285948, ...,  0.76798361,
         0.30397091,  0.4856822 ],
       [ 0.68313241,  0.2044008 ,  0.5817555 , ..., -0.43046448,
         2.9117455 , -0.45163031],
       [ 0.20508126, -0.55507879,  0.14271416, ..., -0.46824866,
        -0.79988359, -1.10665279]])

In [79]:
y_train

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0])

# convert to tensor

In [80]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

#change dtype

X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)

y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

/tmp/ipython-input-587/1555669276.py:10: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype=torch.float32)
/tmp/ipython-input-587/1555669276.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor,dtype=torch.float32)

In [81]:
type(X_train_tensor)

torch.Tensor

In [82]:
X_train.shape[1]

30

In [83]:
import torch.nn as nn

In [84]:
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
      super().__init__()

      self.linear = nn.Linear(num_features,1)
      self.sigmoid = nn.Sigmoid()


    def forward(self,features):
      out = self.linear(features)
      out = self.sigmoid(out)


      return out

In [85]:
torch.rand(30,1)

tensor([[0.3773],
        [0.0936],
        [0.2353],
        [0.2963],
        [0.0505],
        [0.9682],
        [0.4463],
        [0.0544],
        [0.2510],
        [0.1397],
        [0.7011],
        [0.4738],
        [0.8400],
        [0.7688],
        [0.2495],
        [0.7932],
        [0.5228],
        [0.3816],
        [0.6211],
        [0.9328],
        [0.7504],
        [0.4434],
        [0.1248],
        [0.2514],
        [0.1850],
        [0.4302],
        [0.8006],
        [0.2992],
        [0.0135],
        [0.6920]])

In [86]:
X_train_tensor.shape[1]

30

In [87]:
learning_rate = 0.1
epochs=50

In [88]:
loss_function = nn.BCELoss()

In [89]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [90]:
model = MySimpleNN(X_train_tensor.shape[1])

In [91]:
model.parameters()

In [92]:
X_test_tensor.dtype

torch.float32

In [93]:
model.linear.weight.dtype

torch.float32

In [94]:
y_train_tensor.dtype

torch.float32

In [95]:
model.parameters()

In [96]:
#create model

model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor)


  #Loss calculate
  loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))

   #zero gradient
  optimizer.zero_grad()


  #backward pass
  loss.backward()


  #parameter update
  optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.7964539527893066
 2 , Loss = 0.596935510635376
 3 , Loss = 0.4896499216556549
 4 , Loss = 0.42307597398757935
 5 , Loss = 0.3774198293685913
 6 , Loss = 0.3439226746559143
 7 , Loss = 0.3181377649307251
 8 , Loss = 0.29756879806518555
 9 , Loss = 0.28070470690727234
 10 , Loss = 0.26657578349113464
 11 , Loss = 0.2545299530029297
 12 , Loss = 0.24411152303218842
 13 , Loss = 0.23499178886413574
 14 , Loss = 0.22692729532718658
 15 , Loss = 0.21973347663879395
 16 , Loss = 0.21326763927936554
 17 , Loss = 0.2074175626039505
 18 , Loss = 0.20209366083145142
 19 , Loss = 0.1972234547138214
 20 , Loss = 0.1927475482225418
 21 , Loss = 0.1886168271303177
 22 , Loss = 0.18479031324386597
 23 , Loss = 0.18123333156108856
 24 , Loss = 0.17791657149791718
 25 , Loss = 0.17481489479541779
 26 , Loss = 0.17190666496753693
 27 , Loss = 0.16917313635349274
 28 , Loss = 0.16659796237945557
 29 , Loss = 0.1641668975353241
 30 , Loss = 0.16186733543872833
 31 , Loss = 0.15968815982341766
 32 , Loss = 0.15761952102184296
 33 , Loss = 0.15565265715122223
 34 , Loss = 0.15377970039844513
 35 , Loss = 0.15199360251426697
 36 , Loss = 0.15028801560401917
 37 , Loss = 0.14865727722644806
 38 , Loss = 0.1470961719751358
 39 , Loss = 0.14560002088546753
 40 , Loss = 0.1441645324230194
 41 , Loss = 0.14278584718704224
 42 , Loss = 0.1414603590965271
 43 , Loss = 0.14018484950065613
 44 , Loss = 0.13895632326602936
 45 , Loss = 0.13777199387550354
 46 , Loss = 0.1366293579339981
 47 , Loss = 0.13552607595920563
 48 , Loss = 0.134459987282753
 49 , Loss = 0.13342906534671783
 50 , Loss = 0.13243147730827332

In [97]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred= (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6168051958084106

In [98]:
X_train_tensor.shape

torch.Size([455, 30])

In [101]:
!pip install torchinfo

Requirement already satisfied: torchinfo in /usr/local/lib/python3.12/dist-packages (1.8.0)

In [103]:
from torchinfo import summary
summary(model, input_size = (455,30))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
MySimpleNN                               [455, 1]                  --
├─Linear: 1-1                            [455, 1]                  31
├─Sigmoid: 1-2                           [455, 1]                  --
==========================================================================================
Total params: 31
Trainable params: 31
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.01
==========================================================================================
Input size (MB): 0.05
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.06
==========================================================================================