<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/module2DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
w = np.array([2,2])
x = np.array([2,2])
dt = np.dot(w,x)
dt

np.int64(8)

## Normal distribution

In [2]:
random_normal = np.random.randn(3)
random_normal

array([-0.26146813, -1.72494539,  0.63061467])

## Concatation

In [6]:
import pandas as pd
data ={
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [8]:
X = AND.drop('y',axis=1)
y = AND['y']

y.to_frame()

   y
0  0
1  0
2  0
3  1

In [11]:
X.shape

(4, 2)

In [12]:
len(X)

4

In [16]:
bias = np.c_[X,-np.ones((len(X),1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])