<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/module2DeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")
w = np.array([2,2])
x = np.array([2,2])
dt = np.dot(w,x)
dt

np.int64(8)

## Normal distribution

In [45]:
random_normal = np.random.randn(3)
random_normal

array([-0.56974332, -0.40422079,  1.06437787])

## Concatation

In [46]:
import pandas as pd
data ={
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [47]:
X = AND.drop('y',axis=1)
y = AND['y']

y.to_frame()

   y
0  0
1  0
2  0
3  1

In [48]:
X.shape

(4, 2)

In [49]:
len(X)

4

In [50]:
bias = np.c_[X,-np.ones((len(X),1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

In [51]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [-3.20781484e-05  1.26736346e-04  3.06822391e-05]
X with Bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
predicted value after forward pass:
[0 1 0 1]
error:
0    0
1   -1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 0/10:
[-3.20781484e-05 -4.99873264e-01  5.00030682e-01]
for epoch >> 1
predicted value after forward pass:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10:
[4.99967922e-01 1.26736346e-04 3.06822391e-05]
for epoch >> 2
predicted value after forward pass:
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10:
[-3.20781484e-05 -4.99873264e-01  1.00003068e+00]
for epoch >> 3
predicted value after forward pass:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 4
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 5
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 5/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 6
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 6/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 7
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 7/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 8
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 8/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]
for epoch >> 9
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 9/10:
[4.99967922e-01 1.26736346e-04 5.00030682e-01]

In [52]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd
plt.style.use("fivethirtyeight")

In [53]:
class Perceptron:
  def __init__(self,eta,epochs):
    self.weights = np.random.randn(3) * 1e-4
    print(f"self.weights: {self.weights}")
    self.eta = eta
    self.epochs = epochs

  def activationFunction(self,inputs,weights):
    z = np.dot(inputs,weights)
    return np.where(z>0,1,0)

  def fit(self,X,y):
    self.X = X
    self.y = y

    X_with_bias = np.c_[X,-np.ones((len(X),1))]

    print(f"X with Bias:\n{X_with_bias}")

    for epoch in range(self.epochs):
      print(f"for epoch >> {epoch}")

      y_hat = self.activationFunction(X_with_bias,self.weights)
      print(f"predicted value after forward pass: \n{y_hat}")
      self.error = self.y - y_hat
      print(f"error: \n{self.error}")

      self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
      print(f"updated weights after epoch: {epoch}/{self.epochs}: \n{self.weights}")

  def predict(self,X):
    X_with_bias = np.c_[X,-np.ones((len(X),1))]
    return self.activationFunction(X_with_bias,self.weights)

In [54]:
import pandas as pd
data ={
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,0,0,1]
}

AND = pd.DataFrame(data)
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [55]:
X = AND.drop("y", axis=1)
X

   x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [56]:
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [57]:
model = Perceptron(eta = 0.5, epochs=10)
model.fit(X,y)

self.weights: [-1.68567234e-04  7.05277146e-05 -1.40822488e-04]
X with Bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
for epoch >> 0
predicted value after forward pass:
[1 1 0 1]
error:
0   -1
1   -1
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 0/10:
[-1.68567234e-04 -4.99929472e-01  9.99859178e-01]
for epoch >> 1
predicted value after forward pass:
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 1/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 2
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 3
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 4
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 4/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 5
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 5/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 6
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 6/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 7
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 7/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 8
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 8/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]
for epoch >> 9
predicted value after forward pass:
[0 0 0 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 9/10:
[4.99831433e-01 7.05277146e-05 4.99859178e-01]