<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/ReadyDLtraindatasetM_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [155]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [156]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [157]:
df.shape

(569, 33)

In [158]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [159]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [160]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [161]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [162]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [163]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [164]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [165]:
len(df.columns)

31

In [166]:
len(X_train) + len(X_test)

569

In [167]:
X_train

array([[-0.67638018, -0.38439592, -0.66437414, ..., -0.22224207,
        -0.67502066, -0.36235707],
       [ 0.27626752, -0.58901188,  0.27762588, ...,  0.14681683,
         0.79166095,  0.72151752],
       [-0.0742616 , -0.70992131, -0.15078042, ..., -1.07062004,
        -0.57484176, -0.98218248],
       ...,
       [-1.03538985, -0.98429271, -1.01006221, ..., -0.34271998,
         0.17336935,  0.6701387 ],
       [ 1.56813696,  0.473596  ,  1.56243323, ...,  1.94331017,
         1.1015894 ,  0.18477277],
       [-0.79228094, -0.14025187, -0.7931841 , ..., -0.4598428 ,
         0.23598115, -0.89472916]])

In [168]:
y_train

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [169]:
X_train

array([[-0.67638018, -0.38439592, -0.66437414, ..., -0.22224207,
        -0.67502066, -0.36235707],
       [ 0.27626752, -0.58901188,  0.27762588, ...,  0.14681683,
         0.79166095,  0.72151752],
       [-0.0742616 , -0.70992131, -0.15078042, ..., -1.07062004,
        -0.57484176, -0.98218248],
       ...,
       [-1.03538985, -0.98429271, -1.01006221, ..., -0.34271998,
         0.17336935,  0.6701387 ],
       [ 1.56813696,  0.473596  ,  1.56243323, ...,  1.94331017,
         1.1015894 ,  0.18477277],
       [-0.79228094, -0.14025187, -0.7931841 , ..., -0.4598428 ,
         0.23598115, -0.89472916]])

In [170]:
type(y_train)

numpy.ndarray

In [171]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [172]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_326/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_326/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [173]:
type(X_train_tensor)

torch.Tensor

In [174]:
from torch.utils.data import Dataset,DataLoader

In [175]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [176]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [177]:
len(train_dataset)

455

In [178]:
X_train.shape[1]

30

In [179]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [180]:
learning_rate = 0.1
loss_function = nn.BCELoss()

In [181]:
model = MySimpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
batch_size = 32
epochs = 25
n_sample = len(X_train_tensor)
for epoch in range(epochs):
   for start_index in range(0,n_sample,batch_size):
    end_index = start_index + batch_size
   # print(f"Start index {start_index} end index{end_index}")
    X_batch = X_train_tensor[start_index:end_index]
    y_batch = y_train_tensor[start_index:end_index]

    #forward pass
    y_pred = model(X_batch)

    loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #update step
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()



#print step

   print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.1746545135974884
 2 , Loss = 0.0948842391371727
 3 , Loss = 0.06520166248083115
 4 , Loss = 0.049804650247097015
 5 , Loss = 0.040412433445453644
 6 , Loss = 0.03409438952803612
 7 , Loss = 0.029554788023233414
 8 , Loss = 0.026134131476283073
 9 , Loss = 0.023462161421775818
 10 , Loss = 0.021315352991223335
 11 , Loss = 0.01955101452767849
 12 , Loss = 0.018073780462145805
 13 , Loss = 0.016817646101117134
 14 , Loss = 0.015735451132059097
 15 , Loss = 0.0147926090285182
 16 , Loss = 0.013963224366307259
 17 , Loss = 0.013227462768554688
 18 , Loss = 0.012569934129714966
 19 , Loss = 0.01197849866002798
 20 , Loss = 0.01144340168684721
 21 , Loss = 0.010956762358546257
 22 , Loss = 0.010512175038456917
 23 , Loss = 0.010104252956807613
 24 , Loss = 0.009728588163852692
 25 , Loss = 0.00938140694051981

In [182]:
# model evalution
model.eval()
with torch.no_grad():
  y_pred = model(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred.view(-1) == y_test_tensor).float().mean().item()
  print(f"Accuracy = {accuracy}")

Accuracy = 1.0

In [183]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9921875