<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/ReadyDLtraindatasetM_17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [185]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [186]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [187]:
df.shape

(569, 33)

In [188]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [189]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# Train test split

In [190]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [191]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [192]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [193]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [194]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [195]:
len(df.columns)

31

In [196]:
len(X_train) + len(X_test)

569

In [197]:
X_train

array([[-0.14295036,  0.9512839 , -0.19522449, ..., -0.66044408,
        -0.43149984, -0.83063456],
       [-1.81050134,  1.48472625, -1.80507536, ..., -1.748837  ,
         0.24008088,  0.88627263],
       [-0.38355778,  0.77189621, -0.41980711, ..., -0.33319797,
        -0.12961139, -0.18988595],
       ...,
       [ 1.09971621,  0.32106662,  1.08616917, ...,  0.51017759,
         0.55165559, -0.44411475],
       [ 0.94402906,  4.73966872,  0.88088342, ...,  1.3855647 ,
        -0.09086635,  0.05686554],
       [-1.15350154, -0.39412379, -1.13050638, ..., -0.76285072,
        -0.0246769 , -0.4216828 ]])

In [198]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [199]:
X_train

array([[-0.14295036,  0.9512839 , -0.19522449, ..., -0.66044408,
        -0.43149984, -0.83063456],
       [-1.81050134,  1.48472625, -1.80507536, ..., -1.748837  ,
         0.24008088,  0.88627263],
       [-0.38355778,  0.77189621, -0.41980711, ..., -0.33319797,
        -0.12961139, -0.18988595],
       ...,
       [ 1.09971621,  0.32106662,  1.08616917, ...,  0.51017759,
         0.55165559, -0.44411475],
       [ 0.94402906,  4.73966872,  0.88088342, ...,  1.3855647 ,
        -0.09086635,  0.05686554],
       [-1.15350154, -0.39412379, -1.13050638, ..., -0.76285072,
        -0.0246769 , -0.4216828 ]])

In [200]:
type(y_train)

numpy.ndarray

In [201]:
type(y_test)

numpy.ndarray

# Numpy Array to tensors

In [202]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

#change dtype
X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)

#numpy to tensor
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

# y_test_tensor = torch.from_numpy(y_test)

/tmp/ipykernel_326/3826779354.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_train_tensor = torch.tensor(X_train_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test_tensor = torch.tensor(X_test_tensor, dtype=torch.float32)
/tmp/ipykernel_326/3826779354.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_train_tensor = torch.tensor(y_train_tensor,dtype= torch.float32)
/tmp/ipykernel_326/3826779354.py:14: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  y_test_tensor = torch.tensor(y_test_tensor, dtype=torch.float32)

In [203]:
type(X_train_tensor)

torch.Tensor

In [204]:
from torch.utils.data import Dataset,DataLoader

In [205]:
class CustomDataset(Dataset):
  def __init__( self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index], self.labels[index]

In [206]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [207]:
len(train_dataset)

455

In [208]:
X_train.shape[1]

30

In [213]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

In [209]:
import torch.nn as nn
class MySimpleNN(nn.Module):

  def __init__(self,num_features):
    super().__init__()

    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [210]:
learning_rate = 0.1
loss_function = nn.BCELoss()

In [222]:
model = MySimpleNN(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop
epochs = 25
for epoch in range(epochs):
  for batch_features, batch_labels in train_loader:
    y_pred = model(batch_features)

    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


    print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.8022741079330444
 1 , Loss = 0.5646674633026123
 1 , Loss = 0.46786588430404663
 1 , Loss = 0.41602057218551636
 1 , Loss = 0.318813294172287
 1 , Loss = 0.272413969039917
 1 , Loss = 0.2495589405298233
 1 , Loss = 0.2920920252799988
 1 , Loss = 0.289002001285553
 1 , Loss = 0.26928457617759705
 1 , Loss = 0.3222716450691223
 1 , Loss = 0.21692180633544922
 1 , Loss = 0.23653657734394073
 1 , Loss = 0.2816590964794159
 1 , Loss = 0.17089061439037323
 2 , Loss = 0.1730939745903015
 2 , Loss = 0.30019599199295044
 2 , Loss = 0.2026975452899933
 2 , Loss = 0.1645914912223816
 2 , Loss = 0.15881367027759552
 2 , Loss = 0.17005763947963715
 2 , Loss = 0.20462529361248016
 2 , Loss = 0.19831962883472443
 2 , Loss = 0.23423565924167633
 2 , Loss = 0.15920527279376984
 2 , Loss = 0.15673856437206268
 2 , Loss = 0.18484865128993988
 2 , Loss = 0.12094741314649582
 2 , Loss = 0.12568719685077667
 2 , Loss = 0.09967745840549469
 3 , Loss = 0.14194652438163757
 3 , Loss = 0.1123749166727066
 3 , Loss = 0.13386131823062897
 3 , Loss = 0.12291567027568817
 3 , Loss = 0.15174971520900726
 3 , Loss = 0.13727006316184998
 3 , Loss = 0.272054523229599
 3 , Loss = 0.18378350138664246
 3 , Loss = 0.16477279365062714
 3 , Loss = 0.1261887550354004
 3 , Loss = 0.1489274650812149
 3 , Loss = 0.16793157160282135
 3 , Loss = 0.12692618370056152
 3 , Loss = 0.089302659034729
 3 , Loss = 0.019049571827054024
 4 , Loss = 0.12593206763267517
 4 , Loss = 0.13365884125232697
 4 , Loss = 0.09746204316616058
 4 , Loss = 0.1104501336812973
 4 , Loss = 0.10909359157085419
 4 , Loss = 0.10568423569202423
 4 , Loss = 0.14354555308818817
 4 , Loss = 0.15123818814754486
 4 , Loss = 0.21991980075836182
 4 , Loss = 0.09631466865539551
 4 , Loss = 0.1882307082414627
 4 , Loss = 0.1622464805841446
 4 , Loss = 0.12383881956338882
 4 , Loss = 0.07482994347810745
 4 , Loss = 0.030935566872358322
 5 , Loss = 0.08517837524414062
 5 , Loss = 0.07208281010389328
 5 , Loss = 0.1086084172129631
 5 , Loss = 0.11018893122673035
 5 , Loss = 0.10460584610700607
 5 , Loss = 0.14442883431911469
 5 , Loss = 0.21944525837898254
 5 , Loss = 0.07307668030261993
 5 , Loss = 0.1416468620300293
 5 , Loss = 0.1764337420463562
 5 , Loss = 0.062407806515693665
 5 , Loss = 0.15788063406944275
 5 , Loss = 0.0703507587313652
 5 , Loss = 0.11357944458723068
 5 , Loss = 0.2626209855079651
 6 , Loss = 0.09414041042327881
 6 , Loss = 0.1176600381731987
 6 , Loss = 0.1398700773715973
 6 , Loss = 0.05559007078409195
 6 , Loss = 0.17521288990974426
 6 , Loss = 0.09023649990558624
 6 , Loss = 0.16078323125839233
 6 , Loss = 0.08364048600196838
 6 , Loss = 0.17820632457733154
 6 , Loss = 0.09307050704956055
 6 , Loss = 0.16718553006649017
 6 , Loss = 0.09445526450872421
 6 , Loss = 0.09260831028223038
 6 , Loss = 0.04577700048685074
 6 , Loss = 0.01576051115989685
 7 , Loss = 0.0659150779247284
 7 , Loss = 0.10437207669019699
 7 , Loss = 0.14022327959537506
 7 , Loss = 0.12239116430282593
 7 , Loss = 0.10015427321195602
 7 , Loss = 0.07451342046260834
 7 , Loss = 0.04774770885705948
 7 , Loss = 0.08252192288637161
 7 , Loss = 0.07772865146398544
 7 , Loss = 0.07222910970449448
 7 , Loss = 0.08204237371683121
 7 , Loss = 0.200405091047287
 7 , Loss = 0.15001052618026733
 7 , Loss = 0.18551655113697052
 7 , Loss = 0.03071969747543335
 8 , Loss = 0.0882699117064476
 8 , Loss = 0.10742150992155075
 8 , Loss = 0.12491949647665024
 8 , Loss = 0.14445646107196808
 8 , Loss = 0.09123343974351883
 8 , Loss = 0.04725586622953415
 8 , Loss = 0.04180280864238739
 8 , Loss = 0.056828781962394714
 8 , Loss = 0.054369766265153885
 8 , Loss = 0.3076394200325012
 8 , Loss = 0.08621927350759506
 8 , Loss = 0.11536586284637451
 8 , Loss = 0.08548591285943985
 8 , Loss = 0.08725131303071976
 8 , Loss = 0.06026605889201164
 9 , Loss = 0.18286943435668945
 9 , Loss = 0.14146549999713898
 9 , Loss = 0.18188461661338806
 9 , Loss = 0.07285668700933456
 9 , Loss = 0.050056956708431244
 9 , Loss = 0.0694202408194542
 9 , Loss = 0.04340554401278496
 9 , Loss = 0.09486231207847595
 9 , Loss = 0.06787241250276566
 9 , Loss = 0.050041574984788895
 9 , Loss = 0.08179405331611633
 9 , Loss = 0.1617308259010315
 9 , Loss = 0.0901331827044487
 9 , Loss = 0.049989793449640274
 9 , Loss = 0.27345263957977295
 10 , Loss = 0.14425085484981537
 10 , Loss = 0.12969191372394562
 10 , Loss = 0.07412342727184296
 10 , Loss = 0.24500174820423126
 10 , Loss = 0.06342549622058868
 10 , Loss = 0.08582564443349838
 10 , Loss = 0.08080480247735977
 10 , Loss = 0.08835197985172272
 10 , Loss = 0.06290115416049957
 10 , Loss = 0.07299913465976715
 10 , Loss = 0.08196531981229782
 10 , Loss = 0.07386864721775055
 10 , Loss = 0.07583574950695038
 10 , Loss = 0.0745755285024643
 10 , Loss = 0.015979807823896408
 11 , Loss = 0.1827663779258728
 11 , Loss = 0.05068115517497063
 11 , Loss = 0.10474202036857605
 11 , Loss = 0.09521275013685226
 11 , Loss = 0.0968707799911499
 11 , Loss = 0.06629619002342224
 11 , Loss = 0.07185619324445724
 11 , Loss = 0.08235573023557663
 11 , Loss = 0.14448848366737366
 11 , Loss = 0.0377519316971302
 11 , Loss = 0.05448023974895477
 11 , Loss = 0.09630104899406433
 11 , Loss = 0.12532059848308563
 11 , Loss = 0.0993499755859375
 11 , Loss = 0.050960298627614975
 12 , Loss = 0.10091836005449295
 12 , Loss = 0.0820591077208519
 12 , Loss = 0.12957032024860382
 12 , Loss = 0.06137918680906296
 12 , Loss = 0.09335209429264069
 12 , Loss = 0.05263730138540268
 12 , Loss = 0.09592291712760925
 12 , Loss = 0.03479824215173721
 12 , Loss = 0.047136589884757996
 12 , Loss = 0.10337711125612259
 12 , Loss = 0.09504424035549164
 12 , Loss = 0.06486526131629944
 12 , Loss = 0.147176131606102
 12 , Loss = 0.16169598698616028
 12 , Loss = 0.07628915458917618
 13 , Loss = 0.1363871991634369
 13 , Loss = 0.06490485370159149
 13 , Loss = 0.08956453204154968
 13 , Loss = 0.03068036586046219
 13 , Loss = 0.1154303103685379
 13 , Loss = 0.14712966978549957
 13 , Loss = 0.06733109056949615
 13 , Loss = 0.057327836751937866
 13 , Loss = 0.08449157327413559
 13 , Loss = 0.16038864850997925
 13 , Loss = 0.10299736261367798
 13 , Loss = 0.09497907012701035
 13 , Loss = 0.026275675743818283
 13 , Loss = 0.07490501552820206
 13 , Loss = 0.036739375442266464
 14 , Loss = 0.125684916973114
 14 , Loss = 0.17185096442699432
 14 , Loss = 0.07281326502561569
 14 , Loss = 0.04882090166211128
 14 , Loss = 0.05004110559821129
 14 , Loss = 0.04764534905552864
 14 , Loss = 0.07555177807807922
 14 , Loss = 0.14547687768936157
 14 , Loss = 0.04574145749211311
 14 , Loss = 0.056578267365694046
 14 , Loss = 0.16458910703659058
 14 , Loss = 0.05832694470882416
 14 , Loss = 0.03588747978210449
 14 , Loss = 0.126981720328331
 14 , Loss = 0.03807986155152321
 15 , Loss = 0.10057611018419266
 15 , Loss = 0.15899021923542023
 15 , Loss = 0.04012061655521393
 15 , Loss = 0.1102321594953537
 15 , Loss = 0.1264594942331314
 15 , Loss = 0.0927123874425888
 15 , Loss = 0.062314510345458984
 15 , Loss = 0.06419643014669418
 15 , Loss = 0.06254111975431442
 15 , Loss = 0.09710071235895157
 15 , Loss = 0.03443370759487152
 15 , Loss = 0.09770762175321579
 15 , Loss = 0.048505060374736786
 15 , Loss = 0.05376189574599266
 15 , Loss = 0.2890196740627289
 16 , Loss = 0.08147742599248886
 16 , Loss = 0.052556224167346954
 16 , Loss = 0.08028987050056458
 16 , Loss = 0.03132716193795204
 16 , Loss = 0.06609094887971878
 16 , Loss = 0.08547608554363251
 16 , Loss = 0.07713751494884491
 16 , Loss = 0.183259978890419
 16 , Loss = 0.11776086688041687
 16 , Loss = 0.14113515615463257
 16 , Loss = 0.05172199755907059
 16 , Loss = 0.088533416390419
 16 , Loss = 0.1068030521273613
 16 , Loss = 0.024310609325766563
 16 , Loss = 0.04134618118405342
 17 , Loss = 0.10312049835920334
 17 , Loss = 0.09223683178424835
 17 , Loss = 0.07086776196956635
 17 , Loss = 0.07662007212638855
 17 , Loss = 0.08372004330158234
 17 , Loss = 0.054591938853263855
 17 , Loss = 0.08868701756000519
 17 , Loss = 0.06270088255405426
 17 , Loss = 0.10137510299682617
 17 , Loss = 0.05365382879972458
 17 , Loss = 0.059610892087221146
 17 , Loss = 0.07042716443538666
 17 , Loss = 0.040853988379240036
 17 , Loss = 0.04977507144212723
 17 , Loss = 0.7819720506668091
 18 , Loss = 0.05575815960764885
 18 , Loss = 0.07264677435159683
 18 , Loss = 0.1320192515850067
 18 , Loss = 0.06288273632526398
 18 , Loss = 0.1876557618379593
 18 , Loss = 0.03960762172937393
 18 , Loss = 0.04760722070932388
 18 , Loss = 0.041383348405361176
 18 , Loss = 0.048074156045913696
 18 , Loss = 0.11112914979457855
 18 , Loss = 0.13377994298934937
 18 , Loss = 0.0657060444355011
 18 , Loss = 0.061969198286533356
 18 , Loss = 0.08795874565839767
 18 , Loss = 0.09587974101305008
 19 , Loss = 0.04849625751376152
 19 , Loss = 0.07967717945575714
 19 , Loss = 0.05956971272826195
 19 , Loss = 0.19560503959655762
 19 , Loss = 0.13441459834575653
 19 , Loss = 0.04740595445036888
 19 , Loss = 0.06020135059952736
 19 , Loss = 0.07018053531646729
 19 , Loss = 0.07518421858549118
 19 , Loss = 0.06373366713523865
 19 , Loss = 0.057217277586460114
 19 , Loss = 0.08331910520792007
 19 , Loss = 0.09325922280550003
 19 , Loss = 0.08136766403913498
 19 , Loss = 0.007732765283435583
 20 , Loss = 0.0988374575972557
 20 , Loss = 0.12144143134355545
 20 , Loss = 0.035390209406614304
 20 , Loss = 0.053106099367141724
 20 , Loss = 0.08270394802093506
 20 , Loss = 0.10616542398929596
 20 , Loss = 0.033516258001327515
 20 , Loss = 0.06470906734466553
 20 , Loss = 0.1339556872844696
 20 , Loss = 0.06966514885425568
 20 , Loss = 0.15301507711410522
 20 , Loss = 0.03941673785448074
 20 , Loss = 0.02151637338101864
 20 , Loss = 0.10641440749168396
 20 , Loss = 0.0735851526260376
 21 , Loss = 0.06425291299819946
 21 , Loss = 0.08435285091400146
 21 , Loss = 0.04700344800949097
 21 , Loss = 0.034078363329172134
 21 , Loss = 0.07673260569572449
 21 , Loss = 0.09255383163690567
 21 , Loss = 0.11324550211429596
 21 , Loss = 0.04665535315871239
 21 , Loss = 0.06815309822559357
 21 , Loss = 0.043057166039943695
 21 , Loss = 0.062199272215366364
 21 , Loss = 0.014271619729697704
 21 , Loss = 0.3220665752887726
 21 , Loss = 0.05190308392047882
 21 , Loss = 0.010194562375545502
 22 , Loss = 0.02597593143582344
 22 , Loss = 0.24914678931236267
 22 , Loss = 0.02924955263733864
 22 , Loss = 0.05853241682052612
 22 , Loss = 0.07076852023601532
 22 , Loss = 0.09374117851257324
 22 , Loss = 0.0827907845377922
 22 , Loss = 0.1103648692369461
 22 , Loss = 0.01901647076010704
 22 , Loss = 0.051588766276836395
 22 , Loss = 0.05463135242462158
 22 , Loss = 0.09141381829977036
 22 , Loss = 0.10531523823738098
 22 , Loss = 0.04711516946554184
 22 , Loss = 0.1073986366391182
 23 , Loss = 0.05554106459021568
 23 , Loss = 0.1669926643371582
 23 , Loss = 0.13535824418067932
 23 , Loss = 0.04341280087828636
 23 , Loss = 0.11051829904317856
 23 , Loss = 0.035294946283102036
 23 , Loss = 0.048024099320173264
 23 , Loss = 0.09727553278207779
 23 , Loss = 0.103780597448349
 23 , Loss = 0.06075814738869667
 23 , Loss = 0.04094316065311432
 23 , Loss = 0.033920418471097946
 23 , Loss = 0.057739995419979095
 23 , Loss = 0.1092449277639389
 23 , Loss = 0.009254979901015759
 24 , Loss = 0.06063851714134216
 24 , Loss = 0.10947661846876144
 24 , Loss = 0.039882466197013855
 24 , Loss = 0.19055700302124023
 24 , Loss = 0.06753486394882202
 24 , Loss = 0.0502985417842865
 24 , Loss = 0.0897858664393425
 24 , Loss = 0.06400202214717865
 24 , Loss = 0.08266783505678177
 24 , Loss = 0.04934738203883171
 24 , Loss = 0.12439575046300888
 24 , Loss = 0.012427456676959991
 24 , Loss = 0.07618098706007004
 24 , Loss = 0.05599990859627724
 24 , Loss = 0.08187992870807648
 25 , Loss = 0.06385448575019836
 25 , Loss = 0.12412555515766144
 25 , Loss = 0.017965935170650482
 25 , Loss = 0.06301364302635193
 25 , Loss = 0.018783286213874817
 25 , Loss = 0.042278483510017395
 25 , Loss = 0.03349465876817703
 25 , Loss = 0.04430277273058891
 25 , Loss = 0.05282200872898102
 25 , Loss = 0.11543440818786621
 25 , Loss = 0.08683331310749054
 25 , Loss = 0.08692140877246857
 25 , Loss = 0.13773100078105927
 25 , Loss = 0.1920032501220703
 25 , Loss = 0.002975316485390067

In [226]:
#model = MySimpleNN(X_train_tensor.shape[1])
#optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
#batch_size = 32
#epochs = 25
#n_sample = len(X_train_tensor)
#for epoch in range(epochs):
  # for start_index in range(0,n_sample,batch_size):
 #   end_index = start_index + batch_size
   # print(f"Start index {start_index} end index{end_index}")
#    X_batch = X_train_tensor[start_index:end_index]
#    y_batch = y_train_tensor[start_index:end_index]

    #forward pass
 #   y_pred = model(X_batch)

 #   loss = loss_function(y_pred,y_batch.reshape(-1,1))


    #update step
 #   optimizer.zero_grad()
  #  loss.backward()
  #  optimizer.step()



#print step

 #  print(f" {epoch+1} , Loss = {loss.item()} ")

In [230]:
# model evalution
#model.eval()
#with torch.no_grad():
 # y_pred = model(X_test_tensor)
#  y_pred = (y_pred > 0.5).float()
 # accuracy = (y_pred.view(-1) == y_test_tensor).float().mean().item()
 # print(f"Test Accuracy = {accuracy}")

In [231]:
# model evalution
#model.eval()
#with torch.no_grad():
#  y_pred = model(X_train_tensor)
 # y_pred = (y_pred > 0.5).float()
#  accuracy = (y_pred.view(-1) == y_train_tensor).float().mean().item()
 # print(f"Accuracy = {accuracy}")

In [232]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.9765625